pipeline {
    agent any
    stages {
        stage ('Create S3') {
            steps {
               awsCodeBuild(projectName: 'Jenkins', credentialsType:'jenkins', credentialsId: 'CodeBuildJenkins', region: 'ap-south-1', sourceControlType: 'jenkins',buildSpecFile:'')
            }
        }
    }
}
