pipeline {
    agent any
    stages {
        stage ('Create S3') {
            steps {
               awsCodeBuild(projectName: 'project', credentialsType:'jenkins', credentialsId: 'AWSCredentials', region: 'ap-south-1', sourceControlType: 'jenkins',buildSpecFile:'')
            }
        }
    }
}
